<?php
$admin=$_GET["admin"];
$pass=$_GET["pass"];
require 'test_test.php';
if($admin!=""&&file_exists("userss/".$admin)){
    if($pass==file_get_contents("userss/".$admin."/admin/passprotect556")){
        $money=file_get_contents("userss/".$admin."/admin/set/money");
        $vip=file_get_contents("userss/".$admin."/admin/set/viptime");
        $sign=file_get_contents("userss/".$admin."/admin/set/sign");
        $vip=str_replace("minute","分",$vip);
        $vip=str_replace("hour","时",$vip);
        $vip=str_replace("day","天",$vip);
        $vip=str_replace("month","月",$vip);
        $vip=str_replace("year","年",$vip);
        if(file_exists("userss/".$admin."/admin/set/chatname")){
            $name=file_get_contents("userss/".$admin."/admin/set/chatname");
        }else{
            $name="未设置";
        }
        if(file_exists("userss/".$admin."/admin/set/forumtrue")){
            if(file_get_contents("userss/".$admin."/admin/set/forumtrue")=="否"){
                $forumtrue="否";
            }else{
                $forumtrue="是";
            }
        }else{
            $forumtrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/commenttrue")){
            if(file_get_contents("userss/".$admin."/admin/set/commenttrue")=="否"){
                $commenttrue="否";
            }else{
                $commenttrue="是";
            }
        }else{
            $commenttrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/chattrue")){
            if(file_get_contents("userss/".$admin."/admin/set/chattrue")=="否"){
                $chattrue="否";
            }else{
                $chattrue="是";
            }
        }else{
            $chattrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/feedbacktrue")){
            if(file_get_contents("userss/".$admin."/admin/set/feedbacktrue")=="否"){
                $feedbacktrue="否";
            }else{
                $feedbacktrue="是";
            }
        }else{
            $feedbacktrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/registertrue")){
            if(file_get_contents("userss/".$admin."/admin/set/registertrue")=="否"){
                $registertrue="否";
            }else{
                $registertrue="是";
            }
        }else{
            $registertrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/signtrue")){
            if(file_get_contents("userss/".$admin."/admin/set/signtrue")=="否"){
                $signtrue="否";
            }else{
                $signtrue="是";
            }
        }else{
            $signtrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/code")){
            $code=file_get_contents("userss/".$admin."/admin/set/code");
        }else{
            $code="0day";
        }
        if(file_exists("userss/".$admin."/admin/set/codemoney")){
            $codemoney=file_get_contents("userss/".$admin."/admin/set/codemoney");
        }else{
            $codemoney="0";
        }
        if(file_exists("userss/".$admin."/admin/set/loginmoney")){
            $loginmoney=file_get_contents("userss/".$admin."/admin/set/loginmoney");
        }else{
            $loginmoney="0";
        }
        if(file_exists("userss/".$admin."/admin/set/userchattrue")){
            if(file_get_contents("userss/".$admin."/admin/set/userchattrue")=="否"){
                $userchattrue="否";
            }else{
                $userchattrue="是";
            }
        }else{
            $userchattrue="是";
        }
        if(file_exists("userss/".$admin."/admin/set/viplogin")){
            if(file_get_contents("userss/".$admin."/admin/set/viplogin")=="是"){
                $viplogin="是";
            }else{
                $viplogin="否";
            }
        }else{
            $viplogin="否";
        }
        if(file_exists("userss/".$admin."/admin/set/vipcooling")){
            $vipcooling=file_get_contents("userss/".$admin."/admin/set/vipcooling");
        }else{
            $vipcooling="3600";
        }
        if(file_exists("userss/".$admin."/admin/set/moneycooling")){
            $moneycooling=file_get_contents("userss/".$admin."/admin/set/moneycooling");
        }else{
            $moneycooling="3600";
        }
        if(file_exists("userss/".$admin."/admin/set/turncooling")){
            $turncooling=file_get_contents("userss/".$admin."/admin/set/turncooling");
        }else{
            $turncooling="86400";
        }
        if(file_exists("userss/".$admin."/admin/set/collectcooling")){
            $collectcooling=file_get_contents("userss/".$admin."/admin/set/collectcooling");
        }else{
            $collectcooling="86400";
        }
        if(file_exists("userss/".$admin."/admin/set/vipmoney")){
            $vipmoney=file_get_contents("userss/".$admin."/admin/set/vipmoney");
        }else{
            $vipmoney="1.00";
        }
        if(file_exists("userss/".$admin."/admin/set/notpasswords")){
            $notpassset = '否';
        }else{
            $notpassset = '是';
        }
        $code=str_replace("hour","时",$code);
        $code=str_replace("day","天",$code);
        $code=str_replace("month","月",$code);
        $code=str_replace("year","年",$code);
        //获取手续费
        if(file_exists('./userss/'.$admin.'/admin/set/turnshouxu')){
            $shouxu = file_get_contents('./userss/'.$admin.'/admin/set/turnshouxu');
        }else{
            $shouxu = 0;
        }
        //获取手续费
        
        echo "注册送会员:".$vip."<br>注册送金币:".$money."<br>签到送金币:".$sign."<br>管理员昵称:".$name."<br>允许发言:".$chattrue."<br>邀请送会员:".$code."<br>允许发帖:".$forumtrue.'<br>允许评论:'.$commenttrue.'<br>允许注册:'.$registertrue.'<br>允许反馈:'.$feedbacktrue.'<br>允许签到:'.$signtrue.'<br>邀请送金币:'.$codemoney.'<br>允许私聊:'.$userchattrue.'<br> 每日登陆送币:'.$loginmoney.'<br>金币抽奖冷却:'.$moneycooling.'<br>会员抽奖冷却:'.$vipcooling.'<br>只限会员登录:'.$viplogin."<br>会员获币倍数:".$vipmoney.'<br>用户转账冷却:'.$turncooling.'<br>用户收账冷却:'.$collectcooling.'<br>用户能否改密:'.$notpassset.'<br>用户转账手续:'.$shouxu.'<br>';
        
    }else{echo "后台密码错误";}
}else{echo "后台账号不存在";}
?>